basic.forever(function () {
    music.play(music.stringPlayable("C E A D B G F C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 A B D C G E F ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A C5 G C5 A C5 G C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G E C E C E G E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B B F G G F B B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("F B G C F D G A ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G B E G A C5 G B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G D G E C B G E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B C5 B C5 B C5 B C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A G E C5 B C A D ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A B F G E F C D ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C D F E G A C5 B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A C5 G C5 A C5 G C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G E C E C E G E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B B F G G F B B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("F B G C F D G A ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G B E G A C5 G B ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("G D G E C B G E ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("B C5 B C5 B C5 B C5 ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A G E C5 B C A D ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("A B F G E F C D ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C D F E G A C5 B ", 120), music.PlaybackMode.UntilDone)
})
